name = "GregTech Odyssey"
version = "0.1.9-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "106a1ab598b4e663640283dbd78cacedb37a322ccc8a963d163940ec7497ddc6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
