name = "GregTech Odyssey"
version = "0.1.8-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88ac602bee901fb7ea55fad7bdfb964b2439518768b76da56942dc067da150b6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
