name = "GregTech Odyssey"
version = "0.1.7-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac3b458ad7793925a4b2df2b042ed4a955bef107b7becfc399fb0a0dfcd87ccd"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
