name: "Refresh"
on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'mods/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Make packwiz executable
        run: chmod +x .github/localization/packwiz

      - name: Packwiz Refresh
        run: .github/localization/packwiz refresh
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update pack hash