name: "Refresh"
on:
  push:
    paths:
      - 'mods'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make packwiz executable
        run: chmod +x .github/localization/packwiz

      - name: Packwiz Refresh
        run: .github/localization/packwiz refresh
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update pack hash
