name: Sync upstream main → sync

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sync branch
        uses: actions/checkout@v4
        with:
          ref: sync

      - name: Check for upstream changes
        id: check_upstream
        run: |
          git fetch https://github.com/GregTech-Odyssey/GregTech-Odyssey.git main
          UPSTREAM_HASH=$(git rev-parse FETCH_HEAD)
          LOCAL_HASH=$(git rev-parse HEAD)
          echo "::set-output name=has_changes::$([ \"$UPSTREAM_HASH\" != \"$LOCAL_HASH\" ] && echo true || echo false)"

      - name: Sync forked upstream into sync branch
        if: ${{ steps.check_upstream.outputs.has_changes == 'true' }}
        uses: tgymnich/fork-sync@v2.0.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: GregTech-Odyssey
          head: main
          base: sync
          auto_approve: true
          auto_merge: true