name: Sync upstream main → sync

on:
  schedule:
    - cron:  '0,30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `sync` branch
        uses: actions/checkout@v3
        with:
          ref: sync
          fetch-depth: 0
          persist-credentials: true

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/GregTech-Odyssey/GregTech-Odyssey.git
      - name: Fetch upstream `main`
        run: git fetch upstream main

      - name: Compare commits
        id: check
        run: |
          UPSTREAM=$(git rev-parse upstream/main)
          LOCAL=$(git rev-parse HEAD)
          echo "upstream=$UPSTREAM" >> $GITHUB_OUTPUT
          echo "local=$LOCAL"      >> $GITHUB_OUTPUT
      - name: Sync if out-of-date
        if: steps.check.outputs.upstream != steps.check.outputs.local
        run: |
          git reset --hard upstream/main
          git push origin sync --force